import NeuralNetworkStructure.NeuralNetworkUtilities.neuralnetworks as nn
import NeuralNetworkStructure.NeuralNetworkUtilities.scaledconjugategradient as scg
import NeuralNetworkStructure.NeuralNetworkUtilities.TrainUseEval as tue
import NeuralNetworkStructure.NeuralNetworkUtilities.mlutils as ml


